
$lualatex = 'lualatex --recorder --shell-escape -halt-on-error %O %S && cp %D ./%R.pdf';
$pdflatex = 'pdflatex --recorder --shell-escape -halt-on-error %O %S && cp %D ./%R.pdf';
$pdf_mode = 4;
$postscript_mode = $dvi_mode = 0;
$out_dir = ".build";

#$ENV{'TEXINPUTS'}='./packages//:' . $ENV{'TEXINPUTS'};
$ENV{'TEXINPUTS'}='./packages//:';
