dist: trusty
sudo: required

language: generic
services: docker

branches:
  only:
  - master

jobs:
  include:
    - stage: Compile
      before_install: |
        if [ -n "$GITHUB_API_KEY" ]; then
          git remote add upstream https://$GITHUB_USER:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG
          git checkout --orphan $TRAVIS_BRANCH-pdf
          git rm -rf .
          touch Readme.md
          git add Readme.md
          git -c user.name='travis' -c user.email='travis' commit -m "Initial commit"
          git push -q -f upstream $TRAVIS_BRANCH-pdf
          git checkout $TRAVIS_BRANCH
        fi
      
      install:
        - docker pull dxjoke/tectonic-docker
      
      before_script: |
        if [ -n "$GITHUB_API_KEY" ]; then
          git remote add upstream https://$GITHUB_USER:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG
          git fetch upstream
          git checkout $TRAVIS_BRANCH-pdf
          git pull -f -q upstream $TRAVIS_BRANCH-pdf
          git checkout $TRAVIS_BRANCH
        fi

      script: |
          docker run --mount src=$TRAVIS_BUILD_DIR,target=/usr/src/tex,type=bind dxjoke/tectonic-docker \
            /bin/bash -c 'apt-get -qq update;  \
            apt-get -yq --no-install-suggests --no-install-recommends --force-yes install fonts-font-awesome texlive-fonts-extra texlive-latex-recommended; \
            mkdir -p _build; \
            tectonic -o _build coverletter.tex; \
            cp _build/coverletter.pdf coverletter.pdf; \
            for i in "heros" "print" "nocolors" "a4paper" "alegreya" "merriweather" "nunito" "roboto"; do \
              echo "=== Executing option $i ==="; \
              echo "\documentclass[$i]{friggeri-cv}" > .head; \
              tectonic --keep-intermediates --reruns 0 -o _build cv.tex; \
              biber --input-directory _build cv; \
              tectonic --reruns 0 -o _build cv.tex; \
              cp _build/cv.pdf cv-$i.pdf; \
              echo "=== Copying and Clean up ==="; \
              rm -rf _build/*; \
            done'

      after_script: |
        if [ -n "$GITHUB_API_KEY" ]; then
          git stash -q
          git fetch upstream
          git checkout $TRAVIS_BRANCH-pdf
          git pull -q -f upstream $TRAVIS_BRANCH-pdf
          for DOCOPTIONS in heros print nocolors a4paper alegreya merriweather nunito roboto; do
            git checkout -f master cv-$DOCOPTIONS.pdf
            git add -f cv-$DOCOPTIONS.pdf
            git -c user.name='travis' -c user.email='travis' commit -m "current pdf with $DOCOPTIONS option"
            git push -q upstream $TRAVIS_BRANCH-pdf
          done
          git checkout -f master coverletter.pdf
          git add -f coverletter.pdf
          git -c user.name='travis' -c user.email='travis' commit -m "coverletter pdf"
          git push -q upstream $TRAVIS_BRANCH-pdf
        fi

    - stage: Deploy
      install:
        - sudo apt-get -qq update
        - sudo -E apt-get -yq --reinstall --no-install-suggests --no-install-recommends --force-yes install ghostscript imagemagick libmagickcore-dev libmagickwand-dev libmagic-dev
      script: |
        if [ -n "$GITHUB_API_KEY" ]; then
          git remote add upstream https://$GITHUB_USER:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG
          git fetch -q upstream
          git checkout $TRAVIS_BRANCH-pdf
          git pull -f upstream $TRAVIS_BRANCH-pdf
          mkdir -p png
          mogrify -density 288 -resize 25% -format png *.pdf
          mv *.png png/
          git add -f png/*.png
          git -c user.name='travis' -c user.email='travis' commit -m "pngs for readme"
          git push -q upstream $TRAVIS_BRANCH-pdf    
        fi
