# Continous Integration for LaTeX Documents

build:
  tags:
    - gitlab-latex
  before_script:
    - source /etc/profile
    - export TERM="xterm"
    - mkdir .build ; touch .build/paper.not
  script:
    - latexmk -f -lualatex -silent -interaction=nonstopmode paper.tex
  artifacts:
    paths:
      - "paper.pdf"
